config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  
  resources :topic_categories, only: [:index, :show]
  resources :topics
  resources :topic_contents, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :content, ImgUploader
  belongs_to :topic_content, optional: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :topic_category
  belongs_to :user
  has_many :topic_contents
  validates :title, presence: true
  validates :content, presence: true
end

app/models/topic_category.rb
class TopicCategory < ApplicationRecord
  has_many :topics
  validates :name, presence: true
end

app/models/topic_content.rb
class TopicContent < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :images
  validates :content, presence: true
  validates :user_name, presence: true
  accepts_nested_attributes_for :images
end

app/models/user.rb
class User < ApplicationRecord
  before_save :initial_data_set, on: :create
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :topics
  has_many :topic_contents
  
  def initial_data_set
    self.email.downcase!  
    self.image_name = "default_user.jpg" unless image_name.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/topic_categories_controller.rb
class TopicCategoriesController < ApplicationController
  def index
    @topics = Topic.where(topic_category_id: topic_category_id)
  end
  
  def show
    @topics = Topic.where(topic_category_id: params[:id])
  end
end

app/controllers/topic_contents_controller.rb
class TopicContentsController < ApplicationController
  
  
  def create
    @topic = Topic.find(params[:topic_id])
    @topic_content = current_user.topic_contents.build(topic_content_params)
    @topic_content.topic = @topic
    if logged_in?
      @topic_content.user_name = current_user.name
    end
    if @topic_content.save
      flash[:success] = '投稿しました'
      # redirect_to @topic
      redirect_to topic_path(@topic)
    else
      @topic_contents = @topic.topic_contents
      flash.now[:danger] = '投稿できませんでした。'
      render "topics/show"
    end
    
  end
  
  private
  
  def topic_content_params
    params.require(:topic_content).permit(:content, :user_name, images_attributes: [:content])
  end
  
  def images_params
    params.require(:image).permit(:content)
  end 
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create] 
  def index
    @topics = Topic.all.page(params[:page])
  end
  
  def show
    @topic = Topic.find(params[:id])
    if logged_in?
      @topic_content = current_user.topic_contents.build
      3.times do
        @topic_content.images.build
      end
    end
    @topic_contents = @topic.topic_contents
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      flash[:success] = '@topic.titleを作成しました。'
      redirect_to @topic
    else
      flash.now[:danger] = '新規作成に失敗しました。'
      render 'topics/new'
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
  private
  
  def topic_params
    params.require(:topic).permit(:title, :content, :topic_category_id)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    render :layout => 'for_toppages'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit]
  
  def index
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    @user.image_name = "#{@user.id}.jpg"
    image = params[:image]
    if image.present?
      File.binwrite("public/user_images/#{@user.image_name}",image.read)
    end
    if @user.update(params[:user][:password_confirmation].present? ? user_params : user_params_without_password)
      flash[:success] = 'プロフィールを変更しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'プロフィールを変更できませんでした。'
      render :edit
    end
  end
  
  def destroy
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile)
  end
  def user_params_without_password
    params.require(:user).permit(:name, :email, :profile)
  end
  
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top nav-margin">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TennisLove!</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right nav-contents">
          
          <li class="dropdown">
            <a href="#" data-toggle="dropdown">
              掲示板一覧
            <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to '募集', topic_category_path(1) %></li>
              <li><%= link_to '雑談', topic_category_path(2) %></li>
              <li><%= link_to 'その他', topic_category_path(3) %></li>
            </ul>
          </li>
          
          <% if logged_in? %>
            <li>
              <%= link_to user_path(current_user) do %>
                <span class="glyphicon glyphicon-user"></span>ユーザー詳細
              <% end %>
            </li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to '会員登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TennisLove!</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if controller.controller_name == 'toppages' && controller.action_name == 'index' %>
      <div class="top">
        <div class="top-content">
          <h1 class="catch">テニス好きあつまれ！</h1>
          <h2 class="catch-sub">仲間を見つけて一緒にテニスしたり語り合おう</h2>
          <% unless logged_in? %>
            <ul>
              <li class="btn btn-success btn-font"><%= link_to '会員登録', signup_path %></li>
              <li class="btn btn-success btn-font"><%= link_to 'ログイン', login_path %></li>
            </ul>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/for_toppages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TennisLove!</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/topic_categories/show.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <h2>一覧</h2>
    <%= link_to '新規作成', new_topic_path %>
    <ul class="list-group">
      <% @topics.each do |topic| %>
        <li class="list-group-item">
          <h3><%= link_to topic.title, topic_path(topic) %></h3>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/topic_contents/_new.html.erb
<div class="content-form">
  <%= form_for(topic_content) do |f| %>
    <%= hidden_field_tag :topic_id, @topic.id%>
    
    <% unless logged_in? %>
    <div class="form-group">
      <%= f.label :user_name, 'ニックネーム' %>
      <%= f.text_field :user_name, class: 'form-control' %>
    </div>
    <% end %>
    
    <div class="form-group">
      <%= f.text_area :content, class: 'form-control', placeholder: '投稿を作成する' %>
    </div>
    
    <div class="form-group">
      <label>
        <span class="filelabel" title="ファイルを選択">
           <img src="/images/camera-icon.png" width="30" height="30" alt="＋画像">
           選択
        </span>
        <span class="filesend">
          <%= f.fields_for :images do |image| %>
            <%= image.file_field :content,　style: "display:none" %>
          <% end %>
        </span>
      </label>
    </div>
    
    
    <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-offset-sm-2 col-sm-8">
    <h2>一覧</h2>
    <%= link_to '新規作成', new_topic_path %>
    <ul class="list-group">
      <% @topics.each do |topic| %>
        <li class="list-group-item">
          <h3><%= link_to topic.title, topic_path(topic) %></h3>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <h2>新規作成</h2>
    <%= form_for(@topic) do |f| %>
      <div class="form-group">
        <h3>タイトル</h3>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <h3>コメント</h3>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="form-group">
        <h3>カテゴリー</h3>
        <%= f.collection_select :topic_category_id, TopicCategory.all, :id, :name, class: 'form-control' %>
      </div>
      <%= f.submit '新規作成', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <h2><%= @topic.title %></h2>
    <p><%= @topic.content %></p>
    <p>カテゴリ：<%= @topic.topic_category.name %></p>
    <% if logged_in? %>
      <%= render "topic_contents/new", topic_content: @topic_content, topic: @topic %>
    <% end %>
    
    <% @topic_contents.each.with_index(1) do |topic_content,i| %>
      <ul class="content-list">
        <div class="row">
          <div class="col-xs-2">
            <li><img src="<%= "/user_images/#{topic_content.user.image_name}" %>" class="img-responsive"></li>
            <li class="content-name"><%= topic_content.user_name %></li>
          </div>
          <div class="col-xs-10">
            <li class="content-index">No.<%= i %></li>
            <li><%= topic_content.content %></li>
            <% if topic_content.images.present? %>
              <li>
                <ul class="list-inline">
                  <% topic_content.images.each do |image|%>
                    <li><%= image_tag image.content, class:"img-responsive" %></li>
                  <% end %>
                </ul>
              </li>
            </div>
          </div>
        <% end %>
      </ul>
      <hr style="width: 100%; color: black; height: 1px; background-color:black;" />
    <% end %>
  </div>
</div>

app/views/toppages/index.html.erb
<% if controller.controller_name == 'toppages' && controller.action_name == 'index' %>
  <div class="top">
    <div class="top-content">
      <h1 class="catch">テニス好きあつまれ！</h1>
      <h2 class="catch-sub">仲間を見つけて一緒にテニスしたり語り合おう</h2>
      <% unless logged_in? %>
        <ul>
          <li class="btn btn-success btn-font"><%= link_to '会員登録', signup_path %></li>
          <li class="btn btn-success btn-font"><%= link_to 'ログイン', login_path %></li>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

<div class="container">
  <%= render 'layouts/flash_messages' %>
</div>

app/views/users/edit.html.erb
<h2>ユーザー編集</h2>

<%= form_for(@user, :html => {:multipart => true} ) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form-group">
    <label>
      <%= f.label :image_name, 'アイコン' %>
      <span class="filelabel" title="ファイルを選択">
         <img src="/images/camera-icon.png" width="30" height="30" alt="＋画像">
         選択
      </span>
      <input name="image" type="file" style="display: none">
    </label>
  </div>
  
  <div class="form-group">
    <%= f.label :name, 'ニックネーム' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :profile, 'プロフィール' %>
    <%= f.text_area :profile, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit '更新', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <h2>会員登録</h2>
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'ニックネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-offset-2">
    <h2>ユーザー詳細</h2>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-2 col-sm-3">
    <% if @user.image_name.present? %>
      <img src="<%= "/user_images/#{@user.image_name}" %>" class="img-responsive">
    <% else %>
      <img src="<%= "/images/noimage.png" %>" class="img-responsive" style="width:100%">
    <% end %>
  </div>
  <div class="col-sm-6">
    <h3><%= @user.name %></h3>
    <p><%= @user.profile %></p>
  
    <%= link_to '編集', edit_user_path %>
  </div>
</div>